name: Build and Push Docker Image to Huawei Cloud

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'services/**'
      - 'shared/**'
      - 'package.json'
      - 'Dockerfile'
      - 'docker-compose*.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  HUAWEI_REGION: cn-north-4
  HUAWEI_NAMESPACE: ${{ secrets.HUAWEI_NAMESPACE }}
  IMAGE_NAME: wspbot-app
  VERSION: ${{ github.sha }}
  HUAWEI_ACCESS_KEY_ID: ${{ secrets.HUAWEI_ACCESS_KEY_ID }}
  HUAWEI_SECRET_ACCESS_KEY: ${{ secrets.HUAWEI_SECRET_ACCESS_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Huawei Cloud Registry
      uses: docker/login-action@v3
      with:
        registry: swr.${{ env.HUAWEI_REGION }}.myhuaweicloud.com
        username: ${{ env.HUAWEI_ACCESS_KEY_ID }}
        password: ${{ env.HUAWEI_SECRET_ACCESS_KEY }}
        
    - name: Build and push WSPBot App
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          swr.${{ env.HUAWEI_REGION }}.myhuaweicloud.com/${{ env.HUAWEI_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          swr.${{ env.HUAWEI_REGION }}.myhuaweicloud.com/${{ env.HUAWEI_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Update deployment info
      run: |
        echo "🎉 Image built and pushed successfully!"
        echo ""
        echo "📋 Image available:"
        echo "  swr.${{ env.HUAWEI_REGION }}.myhuaweicloud.com/${{ env.HUAWEI_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
        echo "  swr.${{ env.HUAWEI_REGION }}.myhuaweicloud.com/${{ env.HUAWEI_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest"
